name: Cloudflare Workers Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cloudflare/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'cloudflare'
          wranglerVersion: '3.70.0'
          command: deploy --config wrangler-deploy.toml
